const root=document.querySelector('#root'),key='my-drive-v2'
let s=JSON.parse(localStorage.getItem(key)||'{"cols":[],"days":{}}'),d=new Date(),adding=false
const dk=x=>[x.getFullYear(),String(x.getMonth()+1).padStart(2,'0'),String(x.getDate()).padStart(2,'0')].join('-')
const save=()=>localStorage.setItem(key,JSON.stringify(s))
const e=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const value=id=>(s.days[dk(d)]||{})[id]||{improve:'',maintain:'',note:'',done:false}
function card(c){let v=value(c.id);return `<article class="goal-card ${v.done?'done':''}"><header><button data-done="${c.id}">${v.done?'✓':''}</button><h2>${e(c.title)}</h2><button data-delete="${c.id}">×</button></header><label>IMPROVE<textarea data-id="${c.id}" data-field="improve">${e(v.improve)}</textarea></label><label>MAINTAIN<textarea data-id="${c.id}" data-field="maintain">${e(v.maintain)}</textarea></label><label>OPEN NOTE<textarea data-id="${c.id}" data-field="note">${e(v.note)}</textarea></label></article>`}
function render(){let done=s.cols.filter(c=>value(c.id).done).length;root.innerHTML=`<main class="drive-app"><div class="road-scene"></div><header class="top"><div><b>MY DRIVE</b><small>SCROLL TO DRIVE</small></div><span>${done}/${s.cols.length} DONE</span></header><section class="feed">${s.cols.map(card).join('')}<button class="add" data-action="add">＋ CREATE A COLUMN</button></section><section class="journal"><h2>MONTHLY JOURNAL</h2><div class="grid">${Array.from({length:31},(_,i)=>`<button data-day="${i+1}">${i+1}</button>`).join('')}</div></section>${adding?`<div class="modal"><form><button type="button" data-action="close">×</button><small>NEW COLUMN</small><h2>Column title</h2><input autofocus placeholder="Training, Work, Health"><button>Create column</button></form></div>`:''}</main>`}
document.addEventListener('click',ev=>{let a=ev.target.closest('[data-action]')?.dataset.action;if(a==='add'){adding=true;render()}if(a==='close'){adding=false;render()}let id=ev.target.closest('[data-done]')?.dataset.done;if(id){put(id,'done',!value(id).done);render()}id=ev.target.closest('[data-delete]')?.dataset.delete;if(id){s.cols=s.cols.filter(c=>c.id!==id);save();render()}let day=ev.target.closest('[data-day]')?.dataset.day;if(day){d=new Date(d.getFullYear(),d.getMonth(),day);render();scrollTo({top:0,behavior:'smooth'})}})
document.addEventListener('input',ev=>{if(ev.target.matches('textarea'))put(ev.target.dataset.id,ev.target.dataset.field,ev.target.value)})
document.addEventListener('submit',ev=>{if(!ev.target.matches('form'))return;ev.preventDefault();let t=ev.target.querySelector('input').value.trim();if(t){s.cols.push({id:crypto.randomUUID(),title:t});save();adding=false;render()}})
function put(id,f,v){let k=dk(d);s.days[k]||={};s.days[k][id]={...value(id),[f]:v};save()}
addEventListener('scroll',()=>document.documentElement.style.setProperty('--scroll',scrollY),{passive:true});render()
